spring:
  application:
    name: RESTAURANT-MANAGEMENT-SERVICE

  datasource:
    url: jdbc:postgresql://postgres:5432/management?createDatabaseIfNotExist=true
    username: postgres
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

server:
  port: 8082
  servlet:
    context-path: /management

eureka:
  client:
    service-url:
      defaultZone : http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    hostname: eureka-server
